version: '3.8'

services:
  backend:
    build: 
      context: ./SorteoBackend
      dockerfile: Dockerfile
    ports:
      - "5224:5224"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5224
    volumes:
      - ./SorteoBackend:/app
      - ./SorteoBackend/Documentos:/app/Documentos
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-sorteo
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5224/api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
